extends Node

const FINALES = {
	"POSSIBILITY": ["FINALE"],
	"SHOULD": ["FINALE"]}
const HIDDEN_NAME_LEVELS = {
	"POSSIBILITY": [],
	"SHOULD": []}
const LEVELS_UNLOCKED_BY_ALL_CHAINS = {
	"POSSIBILITY": [],
	"SHOULD": ["ANALYSIS_1", "MILITARY_TRAINING"]}
const CHAPTER_CHAINS = [
	["POSSIBILITY", "SHOULD"],
	["SHOULD", "DEFINITION"]]
const LEVEL_CHAINS = {
	"POSSIBILITY": [
		["INTRO", "UNLIKELY"],
		["UNLIKELY", "LOGIC"],
		["LOGIC", "LOGIC_HARD"],
		["LOGIC", "LIES_GENERALIZED"],
		["LIES_GENERALIZED", "LIES_1"],
		["LIES_1", "LIES_2"],
		["LIES_2", "LIES_HARD"],
		["LIES_2", "MEMORY_1"],
		["MEMORY_1", "MEMORY_2"],
		["MEMORY_2", "MEMORY_GENERALIZED"],
		["MEMORY_GENERALIZED", "MEMORY_HARD"],
		["MEMORY_GENERALIZED", "PATTERNS_1"],
		["PATTERNS_1", "PATTERNS_2"],
		["PATTERNS_2", "PATTERNS_3"],
		["PATTERNS_3", "FINALE"]],
	"SHOULD":[
		["INTRO", "ALL_LIVES"],
		["INTRO", "INDIVIDUAL"],
		["INTRO", "CALCULATION"],
		["CALCULATION", "PROBABILITY_1"],
		["PROBABILITY_1", "PROBABILITY_2"],
		["ALL_LIVES", "ANALYSIS_1"],
		["INDIVIDUAL", "ANALYSIS_1"],
		["CALCULATION", "ANALYSIS_1"],
		["ANALYSIS_1", "FIXED_SUM_1"],
		["FIXED_SUM_1", "FIXED_SUM_2"],
		["FIXED_SUM_1", "MILITARY_TRAINING"],
		["ANALYSIS_1", "ANALYSIS_2"],
		["ANALYSIS_2", "MILITARY_TRAINING"],
		["MILITARY_TRAINING", "RICE"],
		["MILITARY_TRAINING", "VEGETARIAN"],
		["RICE", "MATCH"],
		["RICE", "COOPERATE"],
		["VEGETARIAN", "MATCH"],
		["VEGETARIAN", "COOPERATE"],
		["MATCH", "LIE"],
		["COOPERATE", "LIE"],
		["LIE", "SUICIDE"],
		["LIE", "MOSQUITO"],
		["SUICIDE", "CAKE_A"],
		["SUICIDE", "CAKE_B"],
		["MOSQUITO", "CAKE_A"],
		["MOSQUITO", "CAKE_B"],
		["CAKE_A", "FINALE"],
		["CAKE_B", "FINALE"]]}
